#
steps:
- id: go_test #testa a aplicação
  name: "gcr.io/cloud-builders/go"
  args: ["test","gohpa"]
  env: ["GOPATH=go/."]

- name: 'gcr.io/cloud-builders/docker' #Gera uma imagem a partir do projeto
  args:cd
  - 'build'
  - '--build-arg'
  - 'version=1.24.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/go-hpa:latest'
  - 'go/.'

images:
- 'gcr.io/$PROJECT_ID/go-hpa:latest' ##
