apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: go-hpa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: allanlucio/go-hpa
        ports:
        - containerPort: 8000
        resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"